// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDdji4As8cuaKzUl_idMhjOFkUhgk8XJ_s',
    appId: '1:549759014374:web:6a2aa6c3e332c31dfaf227',
    messagingSenderId: '549759014374',
    projectId: 'roome-app-66c39',
    authDomain: 'roome-app-66c39.firebaseapp.com',
    storageBucket: 'roome-app-66c39.appspot.com',
    measurementId: 'G-GRYTP252FN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDPqA4bF98OsuuirbeSUQ4CDZFlONuMq-c',
    appId: '1:549759014374:android:eb57a0f4ac4d6145faf227',
    messagingSenderId: '549759014374',
    projectId: 'roome-app-66c39',
    storageBucket: 'roome-app-66c39.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADcoEJhm1IQ-x_hIuFwol5NR073s9gDSQ',
    appId: '1:549759014374:ios:1d41c176198c9207faf227',
    messagingSenderId: '549759014374',
    projectId: 'roome-app-66c39',
    storageBucket: 'roome-app-66c39.appspot.com',
    iosBundleId: 'com.example.roome',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyADcoEJhm1IQ-x_hIuFwol5NR073s9gDSQ',
    appId: '1:549759014374:ios:3ef4c04ba6c8ddadfaf227',
    messagingSenderId: '549759014374',
    projectId: 'roome-app-66c39',
    storageBucket: 'roome-app-66c39.appspot.com',
    iosBundleId: 'com.example.roome.RunnerTests',
  );
}
