// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB9mwzi2yiM--mOu4Xt490JmPYep7WIJ8U',
    appId: '1:451552389540:web:77307c3ea3a51fa3793931',
    messagingSenderId: '451552389540',
    projectId: 'roome-app-ed23e',
    authDomain: 'roome-app-ed23e.firebaseapp.com',
    storageBucket: 'roome-app-ed23e.appspot.com',
    measurementId: 'G-F9NN8LN4BG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAB3upTEbg36HHHXKwP_Fxh8on-x72lNY4',
    appId: '1:451552389540:android:9d08c8b6dff63456793931',
    messagingSenderId: '451552389540',
    projectId: 'roome-app-ed23e',
    storageBucket: 'roome-app-ed23e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4Wf0V8c14D09r_ZC8BzdkBtjbtzJFbCw',
    appId: '1:451552389540:ios:0dd11d1a9268c2b1793931',
    messagingSenderId: '451552389540',
    projectId: 'roome-app-ed23e',
    storageBucket: 'roome-app-ed23e.appspot.com',
    iosBundleId: 'com.example.roome',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA4Wf0V8c14D09r_ZC8BzdkBtjbtzJFbCw',
    appId: '1:451552389540:ios:89662cc8998f1f3e793931',
    messagingSenderId: '451552389540',
    projectId: 'roome-app-ed23e',
    storageBucket: 'roome-app-ed23e.appspot.com',
    iosBundleId: 'com.example.roome.RunnerTests',
  );
}
